spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: customer
  profiles:
    active: production
  datasource:
    url: ${kodilla_accounts.datasource.url}
    username: ${kodilla_accounts.datasource.username}
    password: ${kodilla_accounts.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${kodilla_accounts.datasource.ddl-mode}
management:
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    name: "customer"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}
eureka:
  client: ${eureka-client}
application:
  allow-get-customer: ${kodilla_accounts.allow-get-customer}
feign:
  hystrix:
    enabled: true